# Generated by Django 2.0 on 2022-11-17 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0004_alter_voting_postproc_alter_voting_tally'),
    ]
    operations = [
        migrations.AddField(
            model_name='question',
            name='yes_no_question',
            field=models.BooleanField(default=False, verbose_name='Yes/No question'),
        ),
    ]
    operations = [
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('C', 'Classic question'),  ('B', 'Yes/No question')], default='C', max_length=1),
        ),
    ]