# Generated by Django 4.1 on 2023-11-20 15:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("voting", "0005_question_type_questionoptionyesno"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="type",
            field=models.CharField(
                choices=[("C", "Classic question"), ("T", "Text question")],
                default="C",
                max_length=1,
            ),
        ),
        migrations.DeleteModel(
            name="QuestionOptionYesNo",
        ),
    ]
