# Generated by Django 4.1 on 2023-11-12 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0005_auto_20221117_2136'),
        ('voting', '0005_question_type_questionoptionyesno'),
    ]

    operations = [
    ]
