# Generated by Django 4.1 on 2023-11-11 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0005_question_type_questinoptionranked'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QuestinOptionRanked',
            new_name='QuestionOptionRanked',
        ),
    ]
