# Generated by Django 4.1 on 2023-11-15 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0006_merge_20231112_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('C', 'Classic question'), ('Y', 'Yes/No question')], default='C', max_length=1),
        ),
    ]
