# Generated by Django 4.1 on 2023-11-11 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0006_rename_questinoptionranked_questionoptionranked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionoptionranked',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ranked_options', to='voting.question'),
        ),
    ]
