# Generated by Django 4.1 on 2023-11-15 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0007_alter_questionoptionranked_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionoptionranked',
            name='preference',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
