# Generated by Django 4.1 on 2023-11-26 19:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("voting", "0008_alter_questionoptionranked_preference"),
    ]

    operations = [
        migrations.AlterField(
            model_name="questionoptionranked",
            name="preference",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
